apiVersion: v1
kind: Pod
metadata:
  name: token-allocator
  labels:
    app: token-allocator
spec:
  containers:
  - name: token-allocator
    image: docker.io/trota/token-allocator:0.0.18
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: allocator-w3-secret-volume
      mountPath: "/home/service/certs"
    - name: astra-tls-volume
      mountPath: "/home/service/astracerts"
    - name: astra-ca-volume
      mountPath: "/home/service/astraca"
  volumes:
  - name: allocator-w3-secret-volume
    secret:
      secretName: allocatorw3secret
  - name: astra-ca-volume
    secret:
      secretName: astraca
  - name: astra-tls-volume
    secret:
      secretName: astratls
---
apiVersion: v1
kind: Service
metadata:
  name: token-allocator-service
spec:
  type: NodePort
  selector:
    app: token-allocator
  ports:
    - name: https
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: token-allocator-ingress
spec:
  rules:
  - http:
      paths:
      - path: /authToken
        backend:
          serviceName: token-allocator-service
          servicePort: 8000
