kind: Pod
apiVersion: v1
metadata:
  name: token-allocator
  labels:
    app: token-allocator
spec:
  containers:
  - name: token-allocator
    image: trota/token-allocator:0.0.1
    volumeMounts:
    - name: secret-volume
      mountPath: "/home/service/certs"
  volumes:
  - name: secret-volume
      secret:
        secretName: allocatorsecret
  - name: allocatorw3secret
      secret:
        secretName: allocatorw3secret
  - name: astraca
      secret:
        secretName: astraca
  - name: astrakey
      secret:
        secretName: astrakey
  - name: astracert
      secret:
        secretName: astracert

---
kind: Service
apiVersion: v1
metadata:
  name: token-allocator-service
spec:
  selector:
    app: token-allocator
  ports:
  - protocol: TCP
    port: 80
    port: 443
    targetPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: token-allocator-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: token-allocator-service
          servicePort: 8000
