kind: Pod
apiVersion: v1
metadata:
  name: token-allocator
  labels:
    app: token-allocator
spec:
  containers:
  - name: token-allocator
    image: docker.io/trota/token-allocator:0.0.5
    ports:
    - containerPort: 8000
    volumeMounts:
    - name: secret-volume
      mountPath: "/home/service/certs"
  volumes:
  - name: secret-volume
    secret:
      secretName: allocatorsecret
  - name: allocatorw3secret
    secret:
      secretName: allocatorw3secret
  - name: astraca
    secret:
      secretName: astraca
  - name: astrakey
    secret:
      secretName: astrakey
  - name: astracert
    secret:
      secretName: astracert
---
apiVersion: v1
kind: Service
metadata:
  name: token-allocator-service
spec:
  selector:
    app: token-allocator
  ports:
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8000
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: token-allocator-ingress
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: token-allocator-service
          servicePort: 8000
