apiVersion: v1
kind: Service
metadata:
  name: token-allocator-service
spec:
  type: NodePort
  selector:
    app: token-allocator
  ports:
    - name: https
      protocol: TCP
      port: 8000
      targetPort: 8000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-allocator
  labels:
    app: token-allocator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: token-allocator
  template:
    metadata:
      labels:
        app: token-allocator
    spec:
      containers:
      - name: token-allocator
        image: docker.io/trota/token-allocator:0.1.18
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /healthz
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
        envFrom:
        - secretRef:
            name: astraadmincreds
        - secretRef:
            name: astratribeappcreds
        - secretRef:
            name: astraapiendpoint
        - secretRef:
            name: astracqlhost
        - secretRef:
            name: astraappmanagerkeyspace
        - secretRef:
            name: astraappkeyspace
        volumeMounts:
        - name: allocator-w3-secret-volume
          mountPath: "/home/service/certs"
        - name: astra-tls-volume
          mountPath: "/home/service/astracerts"
        - name: astra-ca-volume
          mountPath: "/home/service/astraca"
      volumes:
      - name: allocator-w3-secret-volume
        secret:
          secretName: allocatorw3secret
      - name: astra-ca-volume
        secret:
          secretName: astraca
      - name: astra-tls-volume
        secret:
          secretName: astratls
